/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        Huffman h = new Huffman("Hello World!");
    }
}
