/*
 * This source file was generated by the Gradle 'init' task
 */

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        tuiMethod();
    }

    public static void tuiMethod(){
        Scanner scanner = new Scanner(System.in);

        System.out.println("Welcome to Huffman encoder and decoder");


        System.out.println("Please select encoder or decoder");
        System.out.println("1.Encoder");
        System.out.println("2.Decoder");
        System.out.println("3.Exit Program");
        System.out.print("> ");

        int choice = scanner.nextInt();
        scanner.nextLine();

        boolean invalidChoice = true;
        boolean reuse = false;

        while (invalidChoice) {// || reuse) {
            switch (choice){
                case 1:
                    invalidChoice = false;
                    encodingMethod();
                    //reuse = reusePrompt(scanner);
                    break;
                case 2:
                    invalidChoice = false;
                    decodingMethod();
                    //reuse = reusePrompt(scanner);
                    break;
                case 3:
                    invalidChoice = false;
                    break;
                default:
                    invalidChoice = true;
                    System.out.println("Invalid selection, please try again.");
                    continue;
            }

        }
        scanner.close();
        quitMethod();
    }

    public static boolean reusePrompt(Scanner scanner){
        System.out.print("Again? y/N: ");
        String newChoice = scanner.nextLine();
        if (newChoice.equalsIgnoreCase("y")) return true;
        else return false;
    }

    public static void encodingMethod()
    {
        Scanner scanner = new Scanner(System.in);
        String input = "";
        System.out.println("Please select the method for inputting your string.");
        System.out.println("1.Text input");
        System.out.println("2.File input");
        System.out.print("> ");

        int choice = scanner.nextInt();
        scanner.nextLine();

        switch (choice) {
            case 1:
                System.out.print("Please input the text here: ");
                input = scanner.nextLine();

                if (input.isEmpty()) {
                    System.out.println("Empty filename, restarting");
                    tuiMethod();
                } else {
                    Huffman huffman = new Huffman(input);
                    System.out.println(huffman.getEncodedString());
                    System.out.println(huffman.getCompressionPercentage());
                    System.out.print("Would you like to serialize? Y/n: ");
                    String doSerialization = scanner.nextLine();

                    if (!doSerialization.equalsIgnoreCase("n")) {
                        System.out.print("Input a filename for the serialized class: ");
                        String serFileName = scanner.nextLine();
                        // Perform serialization
                        FileIO.Serialize(serFileName, huffman);
                    }
                    System.out.print("Would you like to write it to a file? Y/n: ");
                    String writeToFile = scanner.nextLine();
                    if (!writeToFile.equalsIgnoreCase("n")) {
                        System.out.print("Input a file name/path for the output file: ");
                        String outputFileName = scanner.nextLine();
                        FileIO.writeFile(outputFileName, huffman.getEncodedString());
                    }
                }
                break;

            case 2:
                System.out.print("Please input the file name/path you want to process: ");
                String fileName = scanner.nextLine();
                input = FileIO.readFile(fileName);

                Huffman huffman = new Huffman(input);

                System.out.println(huffman.getEncodedString());
                System.out.println(huffman.getCompressionPercentage());
                System.out.print("Would you like to serialize? Y/n: ");
                String doSerialization = scanner.nextLine();
                if (!doSerialization.equalsIgnoreCase("n")) {
                    System.out.print("Input a filename for the serialized class: ");
                    String serFileName = scanner.nextLine();
                    // Serialization for buffer
                    FileIO.Serialize(serFileName, huffman);
                }

                System.out.print("Would you like to write it to a file? Y/n: ");
                String writeToFile = scanner.nextLine();
                if (!writeToFile.equalsIgnoreCase("n")) {
                    System.out.print("Input a file name/path for the output file: ");
                    String outputFileName = scanner.nextLine();
                    FileIO.writeFile(outputFileName, huffman.getEncodedString());
                }
                break;

            default:
                System.out.println("Incorrect Input");
                break;
        }

        scanner.close();
    }

    public static void quitMethod()
    {
        System.exit(0);
    }

    public static void decodingMethod()
    {
        // Please give .ser file and encoding string
        Scanner scanner = new Scanner(System.in);
        String input = "";
        String fileName = "";
        System.out.println("Please select the method for inputting your string.");
        System.out.println("1.Text input");
        System.out.println("2.File input");
        System.out.print("> ");

        int choice = scanner.nextInt();
        scanner.nextLine();

        switch (choice) {
            case 1:
                System.out.print("Please input the text here: ");
                input = scanner.nextLine();

                if (input.isEmpty()) {
                    System.out.println("Empty filename, restarting");
                    tuiMethod();
                } else {
                    System.out.print("Please input the .ser file name/path to be used: ");
                    String serializedFile = scanner.nextLine();

                    Huffman huffman = new Huffman(input, serializedFile);
                    System.out.println(huffman.getDecodedString());
                    System.out.print("Would you like to write it to a file? Y/n: ");
                    String writeToFile = scanner.nextLine();
                    if (!writeToFile.equalsIgnoreCase("n")) {
                        System.out.print("Input a file name/path for the output file: ");
                        fileName = scanner.nextLine();
                        FileIO.writeFile(fileName, huffman.getDecodedString());
                    }
                }
                break;

            case 2:
                System.out.print("Please input the file name/path you want to process: ");
                fileName = scanner.nextLine();
                input = FileIO.readFile(fileName);
                System.out.print("Please input the .ser file name/path to be used: ");
                String serializedFile = scanner.nextLine();

                Huffman huffman = new Huffman(input, serializedFile);
                System.out.println(huffman.getDecodedString());
                System.out.print("Would you like to write it to a file? Y/n: ");
                String writeToFile = scanner.nextLine();
                if (!writeToFile.equalsIgnoreCase("n")) {
                    System.out.print("Input a file name/path for the output file: ");
                    fileName = scanner.nextLine();
                    FileIO.writeFile(fileName, huffman.getDecodedString());
                }

                break;

            default:
                System.out.println("Incorrect Input");
                break;
        }

        scanner.close();
    }
}
