/*
 * This source file was generated by the Gradle 'init' task
 */
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.text.DecimalFormat;

public class App {

    private static final DecimalFormat decimalFormat = new DecimalFormat("0.00");
    private static final boolean DEBUG = false;
    public static void main(String[] args) {
        tuiMethod();
    }

    public static void tuiMethod(){
        Scanner scanner = new Scanner(System.in);

        System.out.println("Welcome to Huffman encoder and decoder");

        boolean invalidChoice = true;
        boolean reuse = false;

        while (invalidChoice || reuse) {
        System.out.println("Please select encoder or decoder");
        System.out.println("1.Encoder");
        System.out.println("2.Decoder");
        System.out.println("3.Exit Program"); System.out.print("> ");

        int choice = scanner.nextInt();
        scanner.nextLine();
            switch (choice){
                case 1:
                    invalidChoice = false;
                    try {
                        encodingMethod(scanner);
                    }
                    catch (FileNotFoundException e) {
                        if(DEBUG)e.printStackTrace();
                        System.out.println("File not found, or illegal path");
                    }
                    catch (IOException e) {
                        if(DEBUG)e.printStackTrace();
                        System.out.println("There was an issue with system input/output");
                    }
                    reuse = reusePrompt(scanner);
                    break;
                case 2:
                    invalidChoice = false;
                    try {
                        decodingMethod(scanner);
                    }
                    catch (ClassNotFoundException e) {
                        if(DEBUG)e.printStackTrace();
                        System.out.println("Could't find the class");
                    }
                    catch (FileNotFoundException e) {
                        if(DEBUG)e.printStackTrace();
                        System.out.println("File not found, or illegal path");
                    }
                    catch (IOException e) {
                        if(DEBUG)e.printStackTrace();
                        System.out.println("There was an issue with system input/output");
                    }
                    reuse = reusePrompt(scanner);
                    break;
                case 3:
                    reuse = false;
                    invalidChoice = false;
                    break;
                default:
                    invalidChoice = true;
                    System.out.println("Invalid selection, please try again.");
                    continue;
            }

        }
        scanner.close();
        quitMethod();
    }

    public static boolean reusePrompt(Scanner scanner){
        System.out.print("Start over? y/N: ");
        String choice = scanner.nextLine();
        if (choice.equalsIgnoreCase("y")) return true;
        else return false;
    }

    public static String checkInput(String input, Scanner scanner){
        if (input.isEmpty())
        {
            String newFileName = "";
            while (newFileName.isEmpty())
            {
                System.out.print("Recieved empty input, please try again: ");
                newFileName = scanner.nextLine();
            }
            return newFileName;
        }
        return input;
    }


    public static void encodingMethod(Scanner scanner) throws FileNotFoundException, IOException
    {
        String input = "";
        String showEncodedString = "";
        String doSerialization = "";
        String writeToFile = "";
        Huffman huffman;
        System.out.println("Please select the method for inputting your string.");
        System.out.println("1.Text input");
        System.out.println("2.File input");
        System.out.print("> ");

        int choice = scanner.nextInt();
        scanner.nextLine();

        switch (choice) {
            case 1:
                System.out.print("Please input the text here: ");
                input = scanner.nextLine();

                input = checkInput(input, scanner);
                huffman = new Huffman(input);
                System.out.println("Compressed to its " + decimalFormat.format(huffman.getCompressionPercentage()) + "%");
                System.out.print("Would you like to see the encoded text as zeros and ones? Y/n: ");
                showEncodedString = scanner.nextLine();
                if (!showEncodedString.equalsIgnoreCase("n")) {
                    System.out.println(huffman.getEncodedString());
                }

                System.out.print("Would you like to serialize the Huffman class, for decoding the text later? Y/n: ");
                doSerialization = scanner.nextLine();
                if (!doSerialization.equalsIgnoreCase("n")) {
                    System.out.print("Input a file name/path for the serialized class: ");
                    String serFileName = scanner.nextLine();
                    serFileName = checkInput(serFileName, scanner);
                    // Perform serialization
                    FileIO.Serialize(serFileName, huffman);
                }
                System.out.print("Would you like to write the encoded text to a file? Y/n: ");
                writeToFile = scanner.nextLine();
                if (!writeToFile.equalsIgnoreCase("n")) {
                    System.out.print("Input a file name/path for the output file: ");
                    String outputFileName = scanner.nextLine();
                    outputFileName = checkInput(outputFileName, scanner);
                    FileIO.writeBinaryFile(outputFileName, BinaryStringHelper.stringToBytes(huffman.getEncodedString()));
                }
                break;

            case 2:
                System.out.print("Please input the file name/path you want to process: ");
                String fileName = scanner.nextLine();
                fileName = checkInput(fileName, scanner);
                input = FileIO.readFile(fileName);

                huffman = new Huffman(input);

                System.out.println("Compressed to its " + decimalFormat.format(huffman.getCompressionPercentage()) + "%");
                System.out.print("Would you like to see the encoded text as zeros and ones? Y/n: ");
                showEncodedString = scanner.nextLine();
                if (!showEncodedString.equalsIgnoreCase("n")) {
                    System.out.println(huffman.getEncodedString());
                }
                System.out.print("Would you like to serialize the Huffman class, for decoding the text later? Y/n: ");
                doSerialization = scanner.nextLine();
                if (!doSerialization.equalsIgnoreCase("n")) {
                    System.out.print("Input a file name/path for the serialized class: ");
                    String serFileName = scanner.nextLine();
                    serFileName = checkInput(serFileName, scanner);
                    // Serialization for buffer
                    FileIO.Serialize(serFileName, huffman);
                }

                System.out.print("Would you like to write the decoded text to a file? Y/n: ");
                writeToFile = scanner.nextLine();
                if (!writeToFile.equalsIgnoreCase("n")) {
                    System.out.print("Input a file name/path for the output file: ");
                    String outputFileName = scanner.nextLine();
                    outputFileName = checkInput(outputFileName, scanner);
                    FileIO.writeBinaryFile(outputFileName, BinaryStringHelper.stringToBytes(huffman.getEncodedString()));
                }
                break;

            default:
                System.out.println("Incorrect Input");
                break;
        }
    }

    public static void quitMethod()
    {
        System.exit(0);
    }

    public static void decodingMethod(Scanner scanner) throws IOException, FileNotFoundException, ClassNotFoundException
    {
        // Please give .ser file and encoding string
        String input = "";
        String fileName = "";
        String serializedFile = "";
        Huffman huffman;
        System.out.println("Please select the method for inputting your string.");
        System.out.println("1.Text input");
        System.out.println("2.File input");
        System.out.print("> ");

        int choice = scanner.nextInt();
        scanner.nextLine();

        switch (choice) {
            case 1:
                System.out.print("Please input the text here: ");
                input = scanner.nextLine();

                input = checkInput(input, scanner);
                System.out.print("Please input the .ser file name/path to be used: ");
                serializedFile = scanner.nextLine();
                serializedFile = checkInput(serializedFile, scanner);

                huffman = new Huffman(input, serializedFile);
                if(huffman.getDecodedString() != null){
                    System.out.print("Would you like to see the decoded text? Y/n: ");
                    String showDecodedString = scanner.nextLine();
                    if (!showDecodedString.equalsIgnoreCase("n")) {
                        System.out.println(huffman.getDecodedString());
                    }
                    System.out.print("Would you like to write it to a file? Y/n: ");
                    String writeToFile = scanner.nextLine();
                    if (!writeToFile.equalsIgnoreCase("n")) {
                        System.out.print("Input a file name/path for the output file: ");
                        fileName = scanner.nextLine();
                        fileName = checkInput(fileName, scanner);
                        FileIO.writeFile(fileName, huffman.getDecodedString());
                    }
                } else {
                    System.out.println("The returned string was null");
                }
                break;

            case 2:
                System.out.print("Please input the file name/path you want to process: ");
                fileName = scanner.nextLine();
                fileName = checkInput(fileName, scanner);
                byte[] binaryInput = FileIO.readBinaryFile(fileName);
                input = BinaryStringHelper.bytesToString(binaryInput);
                if(DEBUG)System.out.println(input);
                System.out.print("Please input the .ser file name/path to be used: ");
                serializedFile = scanner.nextLine();
                serializedFile = checkInput(serializedFile, scanner);

                huffman = new Huffman(input, serializedFile);
                System.out.print("Would you like to see the decoded text? Y/n: ");
                String showDecodedString = scanner.nextLine();
                if (!showDecodedString.equalsIgnoreCase("n")) {
                    System.out.println(huffman.getDecodedString());
                }
                System.out.print("Would you like to write it to a file? Y/n: ");
                String writeToFile = scanner.nextLine();
                if (!writeToFile.equalsIgnoreCase("n")) {
                    System.out.print("Input a file name/path for the output file: ");
                    fileName = scanner.nextLine();
                    fileName = checkInput(fileName, scanner);
                    FileIO.writeFile(fileName, huffman.getDecodedString());
                }

                break;

            default:
                System.out.println("Incorrect Input");
                break;
        }
    }
}
